LPengine/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('music.urls', namespace='music')),
    path('users/', include('users.urls', namespace='users'))
]

urlpatterns += static(settings.MEDIA_URL,
 
                document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from .views import index_mus, \
    mus_album_table, \
    this_album, \
    user_account, del_pl, del_song

app_name = 'music'

urlpatterns = [
    path('', index_mus, name='index'),
    path('music_albums/', mus_album_table, name='m_albums'),
    path('music_albums/<str:album_title>/', this_album),
    path('profile/', user_account, name='user_account'),
    path('profile/del_pl', del_pl),
    path('profile/del_song', del_song),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.views import auth_login

from .views import logout_view,login_view,register_view



app_name = 'users'

urlpatterns = [
    path('login/', login_view, name = 'login_view'),
    path('logout/', logout_view, name = 'logout_view'),
    path('register/', register_view, name = 'register_view'),
]

music/models.py
import os
from django.db import models
from django.contrib.auth.models import User


class Artist(models.Model):
    title = models.CharField(max_length=20)
    def __str__(self):
        return  self.title

class Album(models.Model):
    title = models.CharField(max_length=50)
    path_cover = models.CharField(max_length=100, blank=True)
    artist = models.ForeignKey(Artist, on_delete = True)
    class Meta:
        verbose_name_plural = 'Альбомы'
    def __str__(self):
        return  self.title

class List_track(models.Model):
    artist = models.ForeignKey(Artist, on_delete = True)
    album = models.ForeignKey(Album, on_delete=True)
    title = models.CharField(max_length=50, blank=True)
    path = models.CharField(max_length=50, blank = True)
    class Meta():
        verbose_name_plural = 'База песен'
    def __str__(self):
        return  self.title

class Playlist(models.Model):
    owner = models.ForeignKey(User, on_delete=True)
    title = models.CharField(max_length=15)
    pl_and_lt = models.ManyToManyField(List_track)
    class Meta:
        verbose_name_plural = 'Плейлисты'
    def __str__(self):
        return self.title



users/models.py
from django.db import models
from django.contrib.auth.models import User
"""
user = User.objects.create_user('user', 'user@user.ru', 'user')
user.first_name = 'John'
user.last_name = 'Citizen'
user.save()
"""
# Create your models here.

music/forms.py
from django import forms
from .models import Playlist


class Form_create_playlist(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['title']
        labels = {'title': ''}


class Form_add_song(forms.ModelForm):
    id_track_model = forms.CharField(max_length=20)

    class Meta:
        model = Playlist
        fields = ['title']
        labels = {'title': 'Название плейлиста'}


class Form_del_song(forms.ModelForm):
    id_track = forms.CharField()

    class Meta:
        model = Playlist
        fields = ['title']


class Form_del_pl(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['title']

users/forms.py
from django import forms
from django.contrib.auth.models import User




class RegForm(forms.Form):
    login = forms.CharField(label='Login')
    password = forms.CharField(label='Password',widget=forms.PasswordInput)


"""
    def clean_login(self):
        data = self.cleaned_data['login']
        return data


"""



music/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .models import Album, List_track, Playlist, Artist
from .forms import Form_create_playlist, Form_add_song, Form_del_song, Form_del_pl


def index_mus(request):
    return render(request, 'music/base.html')


def mus_album_table(request):
    album = Album.objects.all()
    context = {'album': album}
    return render(request, 'music/m_albums.html', context)


def this_album(request, album_title):

    """
        Music album page, function to add a song to the user's playlist
    """

    all_user_pl = Playlist.objects.all()
    album = Album.objects.get(title=album_title)
    # To record through a foreign key model.name_model _set .all()
    tracks = album.list_track_set.all()

    #Form processing
    if request.method != 'POST':
        form = Form_add_song()
    else:
        form = Form_add_song(request.POST)
        if form.is_valid():
            s_form = form.save(commit=False)

            data = (request.POST['title'], request.POST['id_track_model'])  # filed title->id
            playlist = Playlist.objects.get(id=data[0])
            song = List_track.objects.get(id=data[1])

            playlist.pl_and_lt.add(song)

    context = {'album': album,
               'tracks': tracks,
               'form': form,
               'all_user_pl': all_user_pl,
               }
    return render(request, 'music/this_album.html', context)


def user_account(request):
    """
        render two form's, form_del_song and form_del_pl
        Receiving songs on request GET=playlist
    """

    pl = (request.user).playlist_set.all()
    songs_pl = ''
    active_pl = ''
    form_del_song = Form_del_song()
    form_del_pl = Form_del_pl()

    if request.method != 'POST':
        form = Form_create_playlist()

        # Получение списка пл_листов
        if len(request.GET) != 0:
            active_pl = request.GET['pl']

            active_pl = Playlist.objects.get(title=active_pl)

            songs_pl = active_pl.pl_and_lt.all()  # получение связей через поле many to many
    else:

        form = Form_create_playlist(request.POST)
        if form.is_valid():
            new_playlist = form.save(commit=False)
            title = request.POST['title']
            if ((len(Playlist.objects.filter(title=title)) < 1)):
                new_playlist.owner = request.user
                new_playlist.save()

    context = {'form': form,
               'form_del_pl': form_del_pl,
               'form_del_song': form_del_song,
               'user_playlist': pl,
               'songs_pl': songs_pl,
               'active_pl': active_pl}

    return render(request, 'music/user_account.html', context)


def del_pl(request):
    form_del_pl = Form_del_pl(request.POST)
    if form_del_pl.is_valid():
        form_del_pl = form_del_pl.save(commit=False)
        p = Playlist.objects.get(id=request.POST['title'])
        p.delete()
        return HttpResponseRedirect('/index/profile')


def del_song(request):
    form_del_song = Form_del_song(request.POST)
    if form_del_song.is_valid():
        form_del_song = form_del_song.save(commit=False)
        p = Playlist.objects.get(title=request.POST['title'])  #
        t = List_track.objects.get(id=request.POST['id_track'])
        p.pl_and_lt.remove(t)
        return HttpResponseRedirect('/index/profile')

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import RegForm

from django.contrib.auth import logout
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

def login_view(request):
    if request.method != 'POST':
        form = RegForm(initial={'login':'admin', 'password':'admin'})
    else:
        form = RegForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['login']
            password = form.cleaned_data['password']
            user = authenticate(username = username, password = password)
            if user is not None:
                login(request, user)
        return HttpResponseRedirect(reverse('music:index'))
    context = {'form' : form}
    return render(request, 'users/login.html', context)


def register_view(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username = new_user.username,
                                               password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('music:index'))
    return render(request, 'users\egister.html', {'form' : form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('music:index'))

music/templates/music/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> 
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/player.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/menu.css' %}" rel="stylesheet" type="text/css">
    <script  src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script  src="{% static 'js/player.js' %}"></script>
    <script  src="{% static 'js/profile.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Encode+Sans+Condensed" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet"> 
<!--     <meta http-equiv="Refresh" content="3" />     -->

    {% block table_css_album %}
    {% endblock %}
</head>
<body>
    <div class = 'wrapper'>

        <div class = 'header'>

            <div class="logo">
                <a href = '{% url "music:index" %}'><img class="graficlogo" src="{% static 'images/logo.jpg' %}" alt=""></a>
            </div>

        </div>
        
        <div class="topnav">
            <a href = '{% url "music:m_albums" %}'>Студийные альбомы</a>
            <a href = ''>Сборники</a>
            <a href = ''>Мини-альбомы</a>
            <a href = ''>Синглы</a>
            <a href = ''>Концертные альбомы</a>
        </div>


        <div class="content">
            {% block content%}
            {% endblock %}

        </div>
        
        <div class="footer">
                {% if user.is_authenticated %}
                    <a href='{% url "music:user_account" %}'>Откыть плеер</a>
                    <a href = '{% url "users:logout_view" %}'>Выйти</a>
                {% else %}
                    <a href = '{% url "users:login_view" %}' >Log_in</a>
                    <a href = '{% url "users:register_view" %}'>Register</a>
                {% endif %}
        </div>

    </div>
   
</body>
</html>

music/templates/music/m_albums.html
{% extends 'music/base.html' %}
{% load staticfiles %}

{% block content %}

<div class = "albums">
	<div class="album_table">
		{%for alb in album%}
			<a href = '{{alb.title}}'><img src = "/{{alb.path_cover}}" alt = "{{alb.title}}"></a>
	    {%endfor%}
	</div>	    
</div>
{% endblock %}

music/templates/music/self_album.html
{% extends 'music/base.html' %}
{% load staticfiles %}
{% block content %}



<div class="player">
    <div class="control">
        <audio id="my-player" loop ></audio>

        <div class = "player_title">
            <div class="name_album">Linkinpark</div>
            <div class="name_song"></div>
        </div>

        <div class="player_button_control">
            <div class="button_mut">

                    <input id="line_volume" type="range" orient='vertical' min="0" max="100"/>
      
            </div>  
            <div class="back"></div>
            <div class="button" data-src = ""></div>
            <div class="next"></div>
            <div class="but_Playlist"></div>
        </div>

        <div class="time_song">
            <div class="realtime">0:00</div>
            <div class="long">0:00</div>
        </div>

    </div>

    <div class="div_timeline">
        <input id="timeline" type="range" min="0" max=""/>
    </div>

    <div class="tracklist"> 

        <div class="track">
            {% for track in tracks %}
            <div class="track_rows">
                <div class="count"></div>
                <div class='artist-name'>
                    <div class="artist">Linkinpark</div>
                    <div class="name_track" data-src = "/{{track.path}}", aritst='track.artist'>{{track.title}}</div>
                </div>
                <div class="time">0:00</div>
                <div class="add_track" id_track = '{{track.id}}'>AT</div>
            </div>  
            {% endfor %}
        </div> 
                
    </div>
</div>




<div class="select_select">
    <select name="" id="select_add_song">
        {% for pl in all_user_pl%}
            <option id='' value="{{pl.id}}">{{pl}}</option>
        {% endfor %}
    </select>
</div>

<div class="form">
    <form id = 'AddPlaylist' action="" method="POST">
        {% csrf_token %}
        {{form}}
    </form>
</div>

{% endblock %}

music/templates/music/this_album.html
{% extends 'music/base.html' %}
{% load staticfiles %}
{% block content %}



<div class="player">
    <div class="control">
        <audio id="my-player" preload="auto"></audio>

        <div class = "player_title">
            <div class="name_album">Linkinpark</div>
            <div class="name_song"></div>
        </div>

        <div class="player_button_control">
            <div class="button_mut">

                    <input id="line_volume" type="range" orient='vertical' min="0" max="100"/>
      
            </div>  
            <div class="back"></div>
            <div class="button" data-src = ""></div>
            <div class="next"></div>
            <div class="but_Playlist"></div>
        </div>

        <div class="time_song">
            <div class="realtime">0:00</div>
            <div class="long">0:00</div>
        </div>

    </div>

    <div class="div_timeline">
        <input id="timeline" type="range" min="0" max=""/>
    </div>

    <div class="tracklist"> 

        <div class="track">
            {% for track in tracks %}
            <div class="track_rows">
                <div class="arrow"></div>
                <div class="count"></div>
                <div class='artist-name'>
                    <div class="artist">Linkinpark</div>
                    <div class="name_track" data-src = "/{{track.path}}", aritst='track.artist'>{{track.title}}</div>
                </div>
                <div class="time">0:00</div>
                <div class="add_track" id_track = '{{track.id}}'>AT</div>
            </div>  
            {% endfor %}
        </div> 
                
    </div>
</div>




<div class="select_select">
    <select name="" id="select_add_song">
        {% for pl in all_user_pl%}
            <option id='' value="{{pl.id}}">{{pl}}</option>
        {% endfor %}
    </select>
</div>

<div class="form">
    <form id = 'AddPlaylist' action="" method="POST">
        {% csrf_token %}
        {{form}}
    </form>
</div>

{% endblock %}

music/templates/music/user_account.html
{% extends 'music/base.html' %}

{% block content %}

<div class="player">
    <div class="control">
        <audio id="my-player" loop ></audio>

        <div class = "player_title">
            <div class="name_album"></div>
            <div class="name_song"></div>
        </div>

        <div class="player_button_control">
            <div class="button_mut">
                  <input id="line_volume" type="range" orient='vertical' min="0" max="100"/>
            </div>  
            <div class="back"></div>
            <div class="button" data-src = ""></div>
            <div class="next"></div>
            <div class="but_Playlist" id='job_menu'>


                <div class="job_menu">
                    <ul class="top_menu">
                        <li id='job_menu' onclick="$('.create_playlist').show();">
                            Add
                        </li>
                        <li id='job_menu'>Open
                                <ul class="sub_menu">
                                    {% for pl in user_playlist%}
                                    <li><a id='job_menu' href='?pl={{pl}}#'>{{pl}}</a>
                                        <ul class= 'sub_menu_two'>
                                            <li><div id='job_menu' class="button_del_pl" pl={{pl.id}}></div></li>
                                        </ul>
                                    </li>
                                    {% endfor %}
                                </ul>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
        
        <div class="time_song">
            <div class="realtime">0:00</div>
            <div class="long">0:00</div>
        </div>

    </div>

    <div class="div_timeline">
        <input id="timeline" type="range" min="0" max=""/>
    </div>

    <div class="tracklist"> 
        <div class="track">
            {% for song in songs_pl %}
            <div class="track_rows">
                <div class="arrow"></div>
                <div class="count"></div>
                <div class='artist-name'>
                    <div class="artist">Linkinpark</div>
                    <div class="name_track" data-src = "/{{song.path}}", artist='{{song.artist}}'>{{song.title}}</div>
                </div>
                <div class="time">0:00</div>
                <div class="del_track" id_track = '{{song.id}}'>DT</div>
            </div>
            {% endfor %}  
        </div> 
    </div>
</div>


<div class="create_playlist" id='job_menu'>
    <form  class ='form_create_playlist' action="" method="post">    
        {% csrf_token %}
        {{form}}
    </form>
    <div class="button_create_pl">
        <button id="button_create_pl">Добавить</button>
    </div>
</div>



<div class="form_del_track"  active_pl = {{active_pl.title}}>
    <form class="del" action="del_song" method="post">
        {% csrf_token %}    
        {{form_del_song}}
    <button name="submit">Удалить песню</button>
    </form>
</div>



<div class="form_del_pl">
    <form class="del_pl" action="del_pl" method="post">
        {% csrf_token %}
        {{form_del_pl}}
    <button name="submit">Удалить плейлист</button>
    </form>
</div>

{% endblock %}






users/templates/users/egister.html
{% extends 'music/base.html' %}
{% block content%}
<div class="register">
	<form action="" method="POST">
	  {%csrf_token%}
	  {{form.as_p}}
	  <button name="submit">Register</button>
	</form>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'music/base.html' %}
{% block content %}

	<div class="div_login">
		  {% if form.errors %}
		    <p>ОШИБКА</p>
		  {% endif %}
		  <form id="form_login" method="post" action="">
		      {%csrf_token%}
		      {{form.as_p}}
		      <button name = 'submit'>Войти</button>
		  </form>
	</div>

{% endblock %}